### ISSUE TITLE
Unable to upgrade swayfx / scenefx conflicts

### ISSUE THREAD

**Issue by martinstark** [WillPower3309/swayfx#384]
### Please fill out the following:
- **Swayfx Version:**

swayfx version 0.4-b9dcf5f (Dec  2 2024, branch 'master') (based on sway 1.9.0)

- **Description:**
  - Attempt to upgrade swayfx to the latest version in Arch through the AUR

```bash
paru

 Aur (5) scenefx-0.2.1-2  scenefx-0.1-0.1-2  swayfx-0.4-4

 :: Proceed to review? [Y/n]:

looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: installing scenefx (0.2.1-2) breaks dependency 'libscenefx.so=1-64' required by swayfx
loading packages...
resolving dependencies...
looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: installing scenefx (0.2.1-2) breaks dependency 'libscenefx.so=1-64' required by swayfx
loading packages...
resolving dependencies...
looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: installing scenefx (0.2.1-2) breaks dependency 'libscenefx.so=1-64' required by swayfx
loading packages...
resolving dependencies...
looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: installing scenefx (0.2.1-2) breaks dependency 'libscenefx.so=1-64' required by swayfx
loading packages...
resolving dependencies...
looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: installing scenefx (0.2.1-2) breaks dependency 'libscenefx.so=1-64' required by swayfx
error: packages failed to build: scenefx-0.1-0.1-2  swayfx-0.4-4
```

```bash
paru swayfx

error: failed to prepare transaction (could not satisfy dependencies) :: installing scenefx (0.2.1-2) breaks dependency 'libscenefx.so=1-64' required by swayfx
```

```bash
paru scenefx

error: failed to prepare transaction (could not satisfy dependencies)
:: installing scenefx (0.2.1-2) breaks dependency 'libscenefx.so=1-64' required by swayfx
```

**Comment by LAURAilway** [comment]
This is caused by some fun shenanigans in the way that scenefx was updated.
You can force uninstall scenefx (`pacman -Rdd`) and then either just install [scenefx-1.0](https://aur.archlinux.org/packages/scenefx-0.1) or install the newest version of scenefx and 1.0 alongside it.
Note that at the moment, `scenefx-1.0` is the required version.

**Comment by martinstark** [comment]
did swayfx recently change from scenefx to scenefx-1.0? I haven't changed anything manually around this since I installed swayfx, and since `swayfx-0.4-4` was released the other day `paru` wants to install both `scenefx-0.2.1-2` and `scenefx-0.1-0.1-2`

**Comment by WillPower3309** [comment]
> I presume that there were incompatibilities between `scenefx-2.0` and `swayfx-0.4`(the current version), so they made `scenefx-0.2.1` able to be installed alongside the 0.1 version (see [here](https://github.com/wlrfx/scenefx/releases/tag/0.2.1)) and pointed the deps of swayfx specifically to that package until the rebase (0.5, I think) is fully released.

Yup, this was the case. I'll try to sort out this packaging issue

**Comment by WillPower3309** [comment]
Hello, would anyone be able to confirm if the new AUR package update fixes this issue?

**Comment by martinstark** [comment]
without having modified anything since I created this ticket, still cannot install due to the conflict with the original scenefx package

![Image](https://github.com/user-attachments/assets/ef442bd7-8179-4c6b-b2d9-e5e1ed02bc0a)

**Comment by martinstark** [comment]
I believe the scenefx-0.1 package needs to be marked as conflicts with scenefx-0.2, so that I get the option to switch it out during install?

**Comment by johnny32** [comment]
It doesn't work for me yet. I'm getting this error during the install step of yay:

![Image](https://github.com/user-attachments/assets/ea953177-d328-4e63-9363-141d553b1f7d)

Last message says "Install for the following packages failed. A manual intervention is required".

What I understand is swayfx pulls scenefx-0.1 as a dependency, but maybe looks like the error on my screenshot says scenefx (the newer, 0.2 version) dependency is not found. Maybe I'm wrong though.

**Comment by DeliciousHair** [comment]
I am using garuda-sway and can confirm that your fix works there. Thanks!

FWIW, `garuda-update` is a convenience wrapper that uses `pacman` (not `yay`) but I'm a bit of an amateur at all this so I don't know if that is related to the current state not-quite-there for others or not.

**Comment by martinstark** [comment]
> that uses pacman (not yay)

yay also uses pacman, and so does paru. yay and paru are convenience wrappers for pacman.

**Comment by coderj001** [comment]
> It doesn't work for me yet. I'm getting this error during the install step of yay:
> 
> ![Image](https://github.com/user-attachments/assets/ea953177-d328-4e63-9363-141d553b1f7d)
> 
> Last message says "Install for the following packages failed. A manual intervention is required".
> 
> What I understand is swayfx pulls scenefx-0.1 as a dependency, but maybe looks like the error on my screenshot says scenefx (the newer, 0.2 version) dependency is not found. Maybe I'm wrong though.

![Image](https://github.com/user-attachments/assets/6e7fb944-b38a-4278-8df9-8537898d94ce)

I also have the same issue, I tried to install `scenefx-0.1` manually, but still it's not working.

**Comment by WillPower3309** [comment]
@coderj001 @martinstark sorry for the issues here. I believe it should now be fixed

**Comment by LAURAilway** [comment]
> I am using garuda-sway and can confirm that your fix works there. Thanks!
> 
> FWIW, `garuda-update` is a convenience wrapper that uses `pacman` (not `yay`) but I'm a bit of an amateur at all this so I don't know if that is related to the current state not-quite-there for others or not.

Fyi, unless you manually installed the package from the AUR, Garuda uses the [chaotic AUR](https://aur.chaotic.cx/) by default.
That means you are using a precompiled binary for which a workaround has already been pushed by the chaotic AUR maintainers.

**Comment by DeliciousHair** [comment]
Thanks, I should have looked closer. However, I was simply trying to respond to the request to verify the fix worked is all, which I guess I got wrong.

**Comment by martinstark** [comment]
Still an issue 

![Image](https://github.com/user-attachments/assets/faa0b478-78df-493c-915e-32225fe000ef)

**Comment by ErikReider** [comment]
> Still an issue
> 
> ![Image](https://github.com/user-attachments/assets/faa0b478-78df-493c-915e-32225fe000ef)

Fixed now with swayfx 0.5 :)

**Comment by ErikReider** [comment]
And what version of scenefx and swayfx do you have installed? (Through pacman)

**Comment by martinstark** [comment]
@ErikReider you can see at the top of the screenshot for swayfx: 0.4-3. The issues started when 0.4-4 was released with the new dependency chain.

For scenefx, I have the dependency of swayfx 0.4-3 installed: 

![Image](https://github.com/user-attachments/assets/14b081c3-c0c9-4dd2-8d5c-1e8a8916312f)

I know how to "fix" it on my end by removing and reinstalling, but I kept it installed in case you want to keep trying to fix it on your end 😃

**Comment by ErikReider** [comment]
> [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/35975961?v=4&amp;size=80">@ErikReider](https://github.com/ErikReider) you can see at the top of the screenshot for swayfx: 0.4-3. The issues started when 0.4-4 was released with the new dependency chain.
> 
> For scenefx, I have the dependency of swayfx 0.4-3 installed:
> 
> ![Image](https://github.com/user-attachments/assets/14b081c3-c0c9-4dd2-8d5c-1e8a8916312f)
> 
> I know how to "fix" it on my end by removing and reinstalling, but I kept it installed in case you want to keep trying to fix it on your end 😃

Fingers crossed that the new PKGBUILD fixes things 🤞

**Comment by ErikReider** [comment]
Nvm, pacman still doesn't detect that `scenefx-0.1` needs to be installed... I'm clueless

![Image](https://github.com/user-attachments/assets/13b5ed0a-aeb2-469e-a859-285663f6bd65)

**Comment by martinstark** [comment]
Can the ticket be reopened? I'm fairly sure this isn't unique to my setup

**Comment by WillPower3309** [comment]
> Nvm, pacman still doesn't detect that `scenefx-0.1` needs to be installed... I'm clueless
> 
> ![Image](https://github.com/user-attachments/assets/13b5ed0a-aeb2-469e-a859-285663f6bd65)

In this case it doesn't, since you're updating to 0.5

**Comment by WillPower3309** [comment]
So if that installation works (which it should)! It should be good

**Comment by martinstark** [comment]
`paru` (short for `paru -Syu`):

![Image](https://github.com/user-attachments/assets/c85f1dff-a71b-4298-9787-affaaa7c7596)

**Comment by martinstark** [comment]
Want me to keep my broken install, or should I go ahead and just reinstall if this is not a straight forward fix?

**Comment by MagneFire** [comment]
Running into this now as well.

While of course removing both `scenefx-git` and `swayfx-git` before updating works, this is of not very convenient for people who regularly update their system.

To solve this we can also move to the Hyprland approach: Instead of relying on specific .so/library versions, rely on specific `git` packages. This way you don't run into library dependency issues, though at the risk of having the wrong libraries at runtime. But this should only be an issue when `scenefx` updates it's library version while not triggering a rebuild for `swayfx`.

For the specific recent case of the wlroots 0.19 and sway 1.11 rebase this approach works great as both scenefx and swayfx need to be updated.

The only change needed to get this to work is to update the `swayfx-git` PKGBUILD:
```
diff --git a/PKGBUILD b/PKGBUILD
index 0fcaf06..b2ca7bd 100644
--- a/PKGBUILD
+++ b/PKGBUILD
@@ -12,11 +12,11 @@ makedepends=(
 	"wayland-protocols"
 )
 depends=(
+	"scenefx-git"
 	"cairo"
 	"gdk-pixbuf2"
 	"libevdev.so"
 	"libinput"
-	"libscenefx-0.4.so"
 	"libjson-c.so"
 	"libpixman-1.so"
 	"libudev.so"

```

What's your opinion on this approach?

**Comment by WillPower3309** [comment]
Agreed

> Running into this now as well.
> 
> While of course removing both `scenefx-git` and `swayfx-git` before updating works, this is of not very convenient for people who regularly update their system.
> 
> To solve this we can also move to the Hyprland approach: Instead of relying on specific .so/library versions, rely on specific `git` packages. This way you don't run into library dependency issues, though at the risk of having the wrong libraries at runtime. But this should only be an issue when `scenefx` updates it's library version while not triggering a rebuild for `swayfx`.
> 
> For the specific recent case of the wlroots 0.19 and sway 1.11 rebase this approach works great as both scenefx and swayfx need to be updated.
> 
> The only change needed to get this to work is to update the `swayfx-git` PKGBUILD:
> 
> ```
> diff --git a/PKGBUILD b/PKGBUILD
> index 0fcaf06..b2ca7bd 100644
> --- a/PKGBUILD
> +++ b/PKGBUILD
> @@ -12,11 +12,11 @@ makedepends=(
>  	"wayland-protocols"
>  )
>  depends=(
> +	"scenefx-git"
>  	"cairo"
>  	"gdk-pixbuf2"
>  	"libevdev.so"
>  	"libinput"
> -	"libscenefx-0.4.so"
>  	"libjson-c.so"
>  	"libpixman-1.so"
>  	"libudev.so"
> ```
> 
> What's your opinion on this approach?

Agreed!

**Comment by WillPower3309** [comment]
@MagneFire so in your case you want both the git and versioned versions of swayfx and or scenefx?
